package donkers.kevin.orderdk.security;

public enum Permission {
    CAN_ADD_ITEM,
    CAN_ORDER_ITEMS,
    CAN_UPDATE_ITEM,
    CAN_VIEW_OWN_ORDERS,
    CAN_RE_ORDER,
    CAN_VIEW_ALL_ORDERS,
    CAN_VIEW_ALL_CUSTOMERS,
    CAN_VIEW_CUSTOMER_BY_ID,
    CAN_VIEW_SHIPPING_TODAY,
    CAN_VIEW_STOCK,
    CAN_REGISTER
}
