create table addresses
(
    id          bigint generated by default as identity
        primary key,
    country     varchar(255),
    housenumber varchar(255),
    city        varchar(255),
    postal_code varchar(255),
    streetname  varchar(255)
);

alter table addresses
    owner to student;

create table customers
(
    id            bigint generated by default as identity
        primary key,
    email         varchar(255),
    first_name    varchar(255),
    last_name     varchar(255),
    country_code  varchar(255),
    phone_number  varchar(255),
    security_role integer,
    username      varchar(255),
    fk_address_id bigint
        constraint fkibbgjwu63v3h55lky878a8mr0
            references addresses
);

alter table customers
    owner to student;

create table items
(
    id               bigint generated by default as identity
        primary key,
    item_description varchar(255),
    item_name        varchar(255),
    currency         varchar(255),
    unit_price       double precision,
    stock            integer not null
);

alter table items
    owner to student;

create table orders
(
    id         bigint generated by default as identity
        primary key,
    totalprice double precision
);

alter table orders
    owner to student;

create table itembatches
(
    id               bigint generated by default as identity
        primary key,
    amount           integer          not null,
    item_batch_price double precision not null,
    shipping_date    date,
    fk_item_id       bigint
        constraint fk4x76rkw24boqy8malp4a3bcgv
            references items,
    fk_order_id      bigint
        constraint fkho23fhyuevtass4d3awktnqcl
            references orders
);

alter table itembatches
    owner to student;

