create table addresses
(
    id          bigint generated by default as identity primary key,
    country     varchar(255),
    housenumber varchar(255),
    city        varchar(255),
    postal_code varchar(255),
    streetname  varchar(255)
);

create table customers
(
    id            bigint generated by default as identity primary key,
    email         varchar(255),
    first_name    varchar(255),
    last_name     varchar(255),
    country_code  varchar(255),
    phone_number  varchar(255),
    security_role varchar(255),
    username      varchar(255),
    fk_address_id bigint
        constraint fk_address_id
            references addresses
);

create table items
(
    id               bigint generated by default as identity primary key,
    item_description varchar(255),
    item_name        varchar(255),
    currency         varchar(255),
    unit_price       double precision,
    stock            integer not null
);

create table orders
(
    id             bigint generated by default as identity primary key,
    total_price    double precision,
    fk_customer_id bigint
        constraint fk_customer_id
            references customers
);

alter table orders
    owner to student;

create table itembatches
(
    id               bigint generated by default as identity primary key,
    amount           integer          not null,
    item_batch_price double precision not null,
    shipping_date    date,
    fk_item_id       bigint
        constraint fk_item_id
            references items,
    fk_order_id      bigint
        constraint fk_order_id
            references orders
);


